### ISSUE TITLE
add ip/browser info to failed email

### ISSUE THREAD

**Issue by jerzyk** [MarkusH/django-login-canary#5]
there are agent/ip-address info for the successful mail, shouldn't this be an option for the failed email too?

**Comment by MarkusH** [comment]
You can't have that in the failed email because you don't have the request with the information.

**Comment by jerzyk** [comment]
just an idea, raise new exception from the signal handler (e.g. UserFailedException) and then have this handled by middleware - this should be a nice workaround, at least until [patch](https://code.djangoproject.com/ticket/23155) will be implemented
